spring.datasource.url=jdbc:mysql://localhost:/vollmed_api
spring.datasource.username=root
spring.datasource.password=root
spring.flyway.repair-on-migrate=false

app.log-requests=true
logging.level.med.voll.api.RequestLogging=INFO
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%X{req}] %logger{36} - %msg%n
